1.0.0

diff --git a/bin/update_jre b/bin/update_jre
--- a/bin/update_jre
+++ b/bin/update_jre
@@ -37,9 +37,10 @@ Usage:
     update_jre -a [path]
 
 Options:
-    -a      required option. You have read the license at
+    -a      accept license. That is a required option.
+            Please read the license at
             www.oracle.com/technetwork/java/javase/terms/license/index.html
-            and you allow the script to download the JRE.
+            and allow the script to download the JRE by specifying this option.
 
     -k      keep the downloaded .tar.gz, don't remove it at the end.
 
@@ -98,21 +99,38 @@ EOM
 
 }
 
-# Download a webpage and store it in the $HTML variable
+# Download a webpage and store it to a file
+# param1: the website
+# param2: the file
 function downloadWebsite() {
-    local WEBSITE=$1
-    local TEMP_FILE=$2
+    local WEBSITE="$1"
+    local OUTFILE="$2"
 
-    printf "Downloading $WEBSITE ...\n"
-    if [ -f "$TEMP_FILE" ]; then
-        rm "$TEMP_FILE"
+    printf "INFO: Downloading %s and storing it to %s ...\n" "${WEBSITE}" "${OUTFILE}"
+    if [ -f "$OUTFILE" ]; then
+        rm "$OUTFILE"
     fi
-    curl -o "$TEMP_FILE" "$WEBSITE"
-    if [ -f "$TEMP_FILE" ]; then
-        HTML=$(<"$TEMP_FILE")
-        rm "$TEMP_FILE"
+    curl -o "$OUTFILE" "$WEBSITE"
+    if [ ! -f "$OUTFILE" ]; then
+        printf "FATAL: Download of webpage %s failed. Please check your internet connection.\n" "${WEBSITE}"
+        exit 1
+    fi
+}
+
+# Parse a file
+# param1: the file
+# param2: the regex
+function parseFile() {
+    local INFILE="$1"
+    local REGEX=$2
+    if [ -f "$INFILE" ]; then
+        HTML=$(<"$INFILE")
+    fi
+    if [[ "$HTML" =~ $REGEX ]]; then
+        FOUND_ADDRESS="${BASH_REMATCH[1]}"
+        printf "INFO: Found %s in %s\n" "${FOUND_ADDRESS}" "${INFILE}"
     else
-        printf "FATAL: Download of webpage %s failed. Please check your internet connection.\n" "$WEBSITE"
+        printf "FATAL: Actual download address was not found in content of %s\n" "${INFLIE}"
         exit 1
     fi
 }
@@ -163,37 +181,28 @@ function main() {
         mkdir -p "${TARGET_DIR}"
     fi
 
-    printf "Checking for new JRE on the onestop ...\n"
-    downloadWebsite http://www.oracle.com/technetwork/java/javase/downloads/index.html "$TEMP_FILE"
+    printf "Checking for new JRE on the Java onestop page ...\n"
 
-    REGEX='href=\"([^\"]+)\"([^>]+)>[[:space:]]*<img[[:space:]]+alt=\"Download[[:space:]]JRE\"'
+    DOWNLOAD_ADDRESS="http://www.oracle.com/technetwork/java/javase/downloads/index.html"
+    downloadWebsite "$DOWNLOAD_ADDRESS" "$TEMP_FILE"
     # Find the actual JRE download page
     # e.g. <a href="/technetwork/java/javase/downloads/jre10-downloads-4417026.html" target=""><img alt="Download JRE"
-    if [[ "$HTML" =~ $REGEX ]]; then
-        FOUND_ADDRESS=${BASH_REMATCH[1]}
-        DOWNLOAD_ADDRESS="http://www.oracle.com/${FOUND_ADDRESS}"
-        # e.g. http://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html
-        printf "INFO: Found %s\n      in %s\n" ${FOUND_ADDRESS} ${WEBSITE}
-    else
-        printf "FATAL: Actual download address was not found in content of %s\n" ${WEBSITE}
-        exit 1
-    fi
+    REGEX='href=\"([^\"]+)\"([^>]+)>[[:space:]]*<img[[:space:]]+alt=\"Download[[:space:]]JRE\"'
+    parseFile "$TEMP_FILE" $REGEX
 
-    downloadWebsite $DOWNLOAD_ADDRESS "$TEMP_FILE"
-
-    REGEX='(http://download.oracle.com/otn-pub/java/[^_]+_'${OS_TAG}'[^\.]+\.tar.\gz)\"'
+    DOWNLOAD_ADDRESS="http://www.oracle.com/${FOUND_ADDRESS}"
+    downloadWebsite "$DOWNLOAD_ADDRESS" "$TEMP_FILE"
     #  Parse for the .tar.gz file
-    if [[ "$HTML" =~ $REGEX ]]; then
-        FOUND_ADDRESS="${BASH_REMATCH[1]}"
-        DOWNLOAD_ADDRESS="${FOUND_ADDRESS}"
-        # e.g. http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jre-10.0.1_linux-x64_bin.tar.gz
-        printf "INFO: Found %s\n      in %s\n" ${FOUND_ADDRESS} ${WEBSITE}
-    else
-        printf "FATAL: Actual download address was not found in content of %s\n" ${WEBSITE}
-        exit 1
-    fi
+    # e.g. http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jre-10.0.1_linux-x64_bin.tar.gz
+    REGEX='(http://download.oracle.com/otn-pub/java/[^_]+_'${OS_TAG}'[^\.]+\.tar.\gz)\"'
+    parseFile "$TEMP_FILE" $REGEX
 
+    DOWNLOAD_ADDRESS="${FOUND_ADDRESS}"
     THE_TAR_GZ="${TARGET_DIR}/${DOWNLOAD_ADDRESS##*/}"
+
+    # cleanup
+    rm "$TEMP_FILE" 2> /dev/null
+
     # Do we need to download the file actually?
     # Let's check what we have downloaded in the past
     if [ ! -f "${VERSION_FILE}" ]; then
@@ -202,7 +211,7 @@ function main() {
     WEHAVE=$(<"${VERSION_FILE}")
 
     if [ "$DOWNLOAD_ADDRESS" != "$WEHAVE" ] || [ $FORCE -eq 1 ]; then
-       printf "Downloading %s ...\n" $DOWNLOAD_ADDRESS
+       printf "Downloading %s ...\n" "$DOWNLOAD_ADDRESS"
        if [ -f "${THE_TAR_GZ}" ]; then
            rm "${THE_TAR_GZ}"
        fi
