added options -k and -f

diff --git a/bin/update_jre b/bin/update_jre
--- a/bin/update_jre
+++ b/bin/update_jre
@@ -41,6 +41,10 @@ Options:
             www.oracle.com/technetwork/java/javase/terms/license/index.html
             and you allow the script to download the JRE.
 
+    -k      keep the downloaded .tar.gz, don't remove it at the end.
+
+    -f      even if we have the JRE already, update it again.
+
 Parameters:
     path    specifies the path where the JRE should be stored.
             It will be created if it doesn't exist.
@@ -57,7 +61,7 @@ exit 0
 
 function detectOStag() {
     # What OS are we running on?
-    OS=$(uname -s)
+    local OS="$(uname -s)"
     case "$OS" in
         Darwin)
             OS_TAG="osx"
@@ -69,14 +73,14 @@ function detectOStag() {
             OS_TAG="solaris"
             ;;
         *)
-            printf "Not supported on %s\n" "$OS"
+            printf "ERROR: Not supported on %s\n" "$OS"
             exit 1
             ;;
     esac
 }
 
 function licenseAcceptedRequired() {
-    if [ $ACCEPT -eq 0 ]; then
+    if [ $1 -eq 0 ]; then
 cat << EOM
 
 ERROR: In order to allow this script to download the JRE, please read and
@@ -94,48 +98,12 @@ EOM
 
 }
 
-function main() {
-    detectOStag
+# Download a webpage and store it in the $HTML variable
+function downloadWebsite() {
+    local WEBSITE=$1
+    local TEMP_FILE=$2
 
-    # options
-    ACCEPT=0
-    while getopts ':h' OPTION
-    do
-        case $OPTION in
-            a) ACCEPT=1
-               ;;
-            h) usage
-               ;;
-            ?) printf "ERROR: Option -%s is not a supported option.\n" $OPTARG
-               exit 1
-               ;;
-        esac
-    done
-    shift $(($OPTIND -1))
-    licenseAcceptedRequired
-
-    TARGET_DIR="${SCRIPT_DIR}/.jre"
-    # parameters
-    case $# in
-        1) TARGET_DIR="$1"
-           ;;
-        *) printf "ERROR: none or one parameters are supported\n"
-           ;;
-    esac
-
-    VERSION_FILE="${TARGET_DIR}/jre.version"
-
-    # create the configuration directory
-    if [ ! -d "${TARGET_DIR}" ]; then
-        printf "Making directory: %s\n" "${TARGET_DIR}"
-        mkdir -p "${TARGET_DIR}"
-    fi
-
-    WEBSITE=http://www.oracle.com/technetwork/java/javase/downloads/index.html
-    # Download the onestop Java download webpage and store it in the $HTML variable
-    echo "Checking for new JRE on the onestop ..."
-    echo "Downloading $WEBSITE ..."
-    TEMP_FILE=/tmp/jre_onestop.html.$$
+    printf "Downloading $WEBSITE ...\n"
     if [ -f "$TEMP_FILE" ]; then
         rm "$TEMP_FILE"
     fi
@@ -147,6 +115,56 @@ function main() {
         printf "FATAL: Download of webpage %s failed. Please check your internet connection.\n" "$WEBSITE"
         exit 1
     fi
+}
+
+function main() {
+    detectOStag
+
+    # options
+    ACCEPT=0
+    KEEP=0
+    FORCE=0
+    while getopts ':afkh' OPTION
+    do
+        case $OPTION in
+            a) ACCEPT=1
+               ;;
+            f) FORCE=1
+               ;;
+            k) KEEP=1
+               ;;
+            h) usage
+               ;;
+            ?) printf "ERROR: Option -%s is not a supported option.\n" $OPTARG
+               exit 1
+               ;;
+        esac
+    done
+    shift $(($OPTIND -1))
+    licenseAcceptedRequired $ACCEPT
+
+    # parameters
+    case $# in
+        0) TARGET_DIR="${SCRIPT_DIR}/.jre"
+           ;;
+        1) TARGET_DIR="$1"
+           ;;
+        *) printf "ERROR: none or one parameters are supported\n"
+           exit 1
+           ;;
+    esac
+
+    VERSION_FILE="${TARGET_DIR}/jre.version"
+    TEMP_FILE=/tmp/update_jre.$$
+
+    # create the configuration directory
+    if [ ! -d "${TARGET_DIR}" ]; then
+        printf "Making directory: %s\n" "${TARGET_DIR}"
+        mkdir -p "${TARGET_DIR}"
+    fi
+
+    printf "Checking for new JRE on the onestop ...\n"
+    downloadWebsite http://www.oracle.com/technetwork/java/javase/downloads/index.html "$TEMP_FILE"
 
     REGEX='href=\"([^\"]+)\"([^>]+)>[[:space:]]*<img[[:space:]]+alt=\"Download[[:space:]]JRE\"'
     # Find the actual JRE download page
@@ -161,24 +179,11 @@ function main() {
         exit 1
     fi
 
-    WEBSITE=$DOWNLOAD_ADDRESS
-    echo "Checking for new JRE ..."
-    echo "Downloading $DOWNLOAD_ADDRESS ..."
-    TEMP_FILE=/tmp/jre.html.$$
-    if [ -f "$TEMP_FILE" ]; then
-        rm "$TEMP_FILE"
-    fi
-    curl -o "$TEMP_FILE" "$WEBSITE"
-    if [ -f "$TEMP_FILE" ]; then
-        HTML=$(<"$TEMP_FILE")
-        rm "$TEMP_FILE"
-    else
-        printf "FATAL: Download of webpage %s failed. Please check your internet connection.\n" "$WEBSITE"
-        exit 1
-    fi
+    downloadWebsite $DOWNLOAD_ADDRESS "$TEMP_FILE"
 
+    REGEX='(http://download.oracle.com/otn-pub/java/[^_]+_'${OS_TAG}'[^\.]+\.tar.\gz)\"'
     #  Parse for the .tar.gz file
-    if [[ "$HTML" =~ (http://download.oracle.com/otn-pub/java/[^_]+_${OS_TAG}[^\.]+\.tar.\gz)\" ]]; then
+    if [[ "$HTML" =~ $REGEX ]]; then
         FOUND_ADDRESS="${BASH_REMATCH[1]}"
         DOWNLOAD_ADDRESS="${FOUND_ADDRESS}"
         # e.g. http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jre-10.0.1_linux-x64_bin.tar.gz
@@ -188,15 +193,15 @@ function main() {
         exit 1
     fi
 
-    THE_TAR_GZ=${DOWNLOAD_ADDRESS##*/}
+    THE_TAR_GZ="${TARGET_DIR}/${DOWNLOAD_ADDRESS##*/}"
     # Do we need to download the file actually?
     # Let's check what we have downloaded in the past
-    if [ ! -f "${THE_TAR_GZ}" ] || [ ! -f "${VERSION_FILE}" ]; then
+    if [ ! -f "${VERSION_FILE}" ]; then
        printf "%s\n" "none" > "${VERSION_FILE}"
     fi
     WEHAVE=$(<"${VERSION_FILE}")
 
-    if [ "$DOWNLOAD_ADDRESS" != "$WEHAVE" ]; then
+    if [ "$DOWNLOAD_ADDRESS" != "$WEHAVE" ] || [ $FORCE -eq 1 ]; then
        printf "Downloading %s ...\n" $DOWNLOAD_ADDRESS
        if [ -f "${THE_TAR_GZ}" ]; then
            rm "${THE_TAR_GZ}"
@@ -207,7 +212,7 @@ function main() {
            printf "%s\n" "${DOWNLOAD_ADDRESS}" > "${VERSION_FILE}"
 
            echo "Extracting the .tar.gz file ..."
-           gunzip < ${THE_TAR_GZ} | tar xfv - -C ${TARGET_DIR}
+           gunzip < "${THE_TAR_GZ}" | tar xfv - -C "${TARGET_DIR}"
 
            # relative symlink preferred
            BACKUP=$(pwd)
@@ -229,8 +234,10 @@ function main() {
            # restore the folder
            cd "${BACKUP}"
 
-           echo "Clean up ..."
-           rm "${THE_TAR_GZ}"
+           if [ $KEEP -eq 0 ]; then
+               printf "Clean up ...\n"
+               rm "${THE_TAR_GZ}"
+           fi
        else
            printf "FATAL: Download failed.\n"
            exit 1
