added adoptopenjdk.net's openjdk10 and openjdk10-openj9, and respect -az for existing jdk downloads

diff --git a/bin/update_jre b/bin/update_jre
--- a/bin/update_jre
+++ b/bin/update_jre
@@ -32,27 +32,35 @@ usage() {
 cat << END
 update_jre v${SCRIPT_VERSION}, Copyright 2018 Johann N. Loefflmann
 
-Downloads the latest x64 JRE/JDK tarball resp. the latest tzupdater zip
-from the web, extracts it and creates/updates a symlink called <type>_latest
-or tzupdater.jar. Supports multiple sources, such as oracle.com, java.com,
-jdk.java.net, and adoptopenjdk.net. The OS flavor of the JRE/JDK is determined
-by the OS that you are running. Linux and macOS are supported.
+Downloads the latest x64 JRE/JDK tarball resp. the latest tzupdater zip from
+the web, extracts it and creates/updates a symlink called <type>_latest
+resp. tzupdater.jar. Supports multiple sources, such as oracle.com, java.com,
+jdk.java.net, and adoptopenjdk.net. The latest timezone database can be applied
+to the requested JRE/JDK as well so that you have the most possible up to date
+JRE/JDK within a Java family from your preferred source. And since the symlink
+always points to the latest JRE/JDK you can update the JRE/JDK both fast and
+comfortable. The OS flavor of the JRE/JDK is determined by the OS that you are
+running. Linux and macOS are supported.
 
 Usage:
     update_jre [ [-h] | [-a] [-d] [-f] [-k] [-s source] [-t type] [path] ]
 
 Options:
     -a      accept license. That is a required option if you want to
-            download the JRE, JDK or tzupdater from the Oracle site (-t oracle.com).
-            Please read the license at
+            download the JRE, JDK or tzupdater from the Oracle site
+            (-t oracle.com). Please read the license at
             www.oracle.com/technetwork/java/javase/terms/license/index.html
             resp. at
-            http://www.oracle.com/technetwork/java/javasebusiness/downloads/tzupdater-lic-354297.txt
-            and allow the script to download the package by specifying this option.
+            http://www.oracle.com/technetwork/java/javasebusiness/downloads/
+            L-> tzupdater-lic-354297.txt
+            and allow the script to download the package by specifying this
+            option.
 
-    -d      dry run. Don't download the JRE, JDK or tzupdater, just inform the user.
+    -d      dry run. Don't download the JRE, JDK or tzupdater, just inform the
+            user.
 
-    -f      force. Even if we have the JRE, JDK or tzupdater already, update it again.
+    -f      force. Even if we have the JRE, JDK or tzupdater already, update it
+            again.
 
     -h      prints this help.
 
@@ -82,16 +90,19 @@ Options:
             For -s adoptopenjdk.net it can be
                 openjdk8          (OpenJDK 8 with Hotspot)
                 openjdk8-openj9   (OpenJDK 8 with OpenJ9)
+                openjdk10         (OpenJDK 10 with Hotspot)
+                openjdk10-openj9  (OpenJDK 10 with OpenJ9)
 
     -v      version. Prints out the version of this script.
 
     -z      after the JRE or JDK has been downloaded and extracted, the
             latest tzupdater will be downloaded and applied to the JRE or JDK.
+            Requires -a to work.
 
 Parameters:
     path    specifies the path where the JRE, JDK or tzupdater should be stored.
             It will be created if it doesn't exist.
-            If omitted, .jre/, .sjre/, .jdk/, or .tzupdater/ will be used.
+            If omitted, .<type>/ will be used.
 
 Examples:
     ./update_jre -a
@@ -108,9 +119,12 @@ Examples:
     ./update_jre -a -t tzupdater /opt/java/
             updates the tzupdater in /opt/java/ and it updates a symlink
             called tzupdater.jar there.
-    ./update_jre -azfs adoptopenjdk.net -t openjdk8
-            download the OpenJDK8 from adoptopenjdk.net (even if downloaded
-            already) and apply the latest timezone database from oracle.com.
+    ./update_jre -az -s adoptopenjdk.net -t openjdk10
+            download both the latest tzupdater from oracle.com and
+            the latest OpenJDK10 build from adoptopenjdk.net, apply the
+            latest timezone database from IANA to the OpenJDK by calling
+            the tzupdater tool. Symlink called .opendk10/openjdk10_latest
+            will point to the latest and updated OpenJDK10 build.
 END
 exit 0
 }
@@ -146,7 +160,8 @@ ERROR: In order to allow this script to download the latest JRE, Server JRE
 
        In order to allow this script to download the latest tzupdater from
        oracle.com, please read and accept the license at
-       http://www.oracle.com/technetwork/java/javasebusiness/downloads/tzupdater-lic-354297.txt
+       http://www.oracle.com/technetwork/java/javasebusiness/downloads/
+       L-> tzupdater-lic-354297.txt
        by specifying the -a option to this script.
 
        Use option -h to get more help.
@@ -210,9 +225,9 @@ function main() {
                ;;
             d) DRYRUN=1
                ;;
-            h) usage
-               ;;
             f) FORCE=1
+               ;;
+            h) usage
                ;;
             k) KEEP=1
                ;;
@@ -260,13 +275,17 @@ function main() {
         if [ "$OS_TAG" = "linux" ]; then
             OS_TAG="Linux"
         fi
-	    if [ "$TYPE" != "openjdk8" ] && [ "$TYPE" != "openjdk8-openj9" ]; then
+	    if [ "$TYPE" != "openjdk8" ] && [ "$TYPE" != "openjdk8-openj9" ] && \
+	       [ "$TYPE" != "openjdk10" ] && [ "$TYPE" != "openjdk10-openj9" ]; then
             printf "ERROR: type %s is not supported by %s.\n" "$TYPE" "$SOURCE"
             exit 1
         fi
-        if [ "$OS_TAG" = "Mac" ] && [ "$TYPE" = "openjdk8-openj9" ]; then
-            printf "ERROR: type %s (a JDK .tar.gz) is not supported on macOS by %s.\n" "$TYPE" "$SOURCE"
-            exit 1
+        # there is no openj9 on Mac
+        if [ "$OS_TAG" = "Mac" ]; then
+            if [ "$TYPE" = "openjdk8-openj9" ] || [ "$TYPE" = "openjdk10-openj9" ]; then
+                printf "ERROR: type %s (a JDK .tar.gz) is not supported on macOS by %s.\n" "$TYPE" "$SOURCE"
+                exit 1
+            fi
         fi
     fi
 
@@ -451,7 +470,13 @@ function main() {
            exit 1
        fi
     else
-       printf "Skipping download, because it seems that have downloaded %s already in the past. Use -f to force a download.\n" $DOWNLOAD_ADDRESS
+       printf "Skipping download, because it seems that you have downloaded %s already in the past. Use -f to force a download.\n" $DOWNLOAD_ADDRESS
+
+       # any jre, sjre or jdk, etc. with -z option is wanted
+       if [ "$TYPE" != "tzupdater" ] && [ $ZOPTION -eq 1 ]; then
+           # call the tzupdater by using the java binary from the JRE/JDK that we downloaded in the past
+           "${TARGET_DIR}/${TYPE}_latest/bin/java" -jar "${TARGET_DIR}/tzupdater.jar" -v -l
+       fi
     fi
 }
 
